### PR TITLE
[16.0][IMP] stock_location_orderpoint: Incremental run of cron rules

### PR DESCRIPTION
**Pull request by lmignon**
cc  @jbaudoux @rousseldenis

### CODE REVIEW

**Comment by rousseldenis** [comment]
@jbaudoux @mt-software-de This has not been reviewed yet.

**Comment by mt-software-de** [comment]
> @jbaudoux @mt-software-de This has not been reviewed yet.

We can now open an PR for oca/stock-logistics-orderpoint ?

**Comment by rousseldenis** [comment]
> > @jbaudoux @mt-software-de This has not been reviewed yet.
> 
> We can now open an PR for oca/stock-logistics-orderpoint ?

Yes we should. I'll do it

**Comment by mt-software-de** [comment]
Closed will be moved as PR to https://github.com/OCA/stock-logistics-orderpoint/

**Pull request closed without merging**
